### ISSUE TITLE
Linux mint 21 support

### ISSUE THREAD

**Issue by proJM-Coding** [NicklasVraa/NovaOS-nord-Theme#3]
I have seen a few people having problems using the theme for linux mint 21. This is mentioned in the read.md file "Only tested on Linux Mint 20" and #1 shows that it doesn't work well. 

When can we see support for linux mint 21 if there is going to be any at all?

**Comment by NicklasVraa** [comment]
I've tested it on Mint 21 now, and it works just fine :)

**Comment by ghost** [comment]
Thank you so much, can't wait to use it!
